version: "3"

services:

    config-service:
        build: ./services/config-service
        image: bphun/spotify-client-images:config-service
        ports:
            - 8888:8888
        container_name: config-service
        networks: 
            - serviceNet 

    service-discovery:
        build: ./services/service-discovery
        image: bphun/spotify-client-images:service-discovery
        ports: 
            - 8761:8761
        container_name: service-discovery
        depends_on: 
            - config-service
        environment: 
            - DOCKER_CONFIG_PROFILE=docker
        networks:
            - serviceNet
        restart: on-failure
        links: 
            - config-service

    api-gateway:
        build: ./services/api-gateway
        image: bphun/spotify-client-images:api-gateway
        ports:
            - 9000:9000
        container_name: api-gateway
        depends_on: 
            - service-discovery
            - config-service
        environment: 
            - DOCKER_CONFIG_PROFILE=docker
        networks:
            - serviceNet
        restart: on-failure
        links: 
            - config-service
            - service-discovery

    authentication-service:
        build: ./services/authentication-service
        image: bphun/spotify-client-images:authentication-service
        ports:
            - 8090:8090
        container_name: authentication-service
        environment: 
            - DOCKER_CONFIG_PROFILE=docker
        depends_on: 
            - service-discovery
            - config-service
            - mysqldatabase
        networks:
            - serviceNet
        restart: on-failure
        links: 
            - config-service
            - mysqldatabase
            - service-discovery

    mysqldatabase:
        build: ./services/database
        image: bphun/spotify-client-images:mysqldatabase
        ports:
            - 3306:3306
        container_name: mysqldatabase
        networks:
            - serviceNet

    movie-info-service:
        build: ./services/movie-info-service
        image: bphun/spotify-client-images:movie-info-service
        ports:
            - 8081:8081
        container_name: movie-info-service
        environment: 
            - DOCKER_CONFIG_PROFILE=docker
        depends_on: 
            - service-discovery
            - config-service
        networks:
            - serviceNet
        restart: on-failure
        links: 
            - config-service
            - service-discovery

    movie-rating-service:
        build: ./services/movie-rating-service
        image: bphun/spotify-client-images:movie-rating-service
        ports:
            - 8082:8082
        container_name: movie-rating-service
        environment: 
            - DOCKER_CONFIG_PROFILE=docker
        depends_on: 
            - service-discovery
            - config-service
        networks:
            - serviceNet
        restart: on-failure
        links: 
            - config-service
            - service-discovery

    movie-catalog-service:
        build: ./services/movie-catalog-service
        image: bphun/spotify-client-images:movie-catalog-service
        ports:
            - 8080:8080
        container_name: movie-catalog-service
        environment: 
            - DOCKER_CONFIG_PROFILE=docker
        depends_on: 
            - service-discovery
            - config-service
        networks:
            - serviceNet
        restart: on-failure
        links: 
            - config-service
            - service-discovery

networks:
    serviceNet: